/* 
 * RSMeans Consumer REST API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using Gordian.DataApi.Client;
using Gordian.DataApi.Model;
using RestSharp;

namespace Gordian.DataApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICostDataUnitEquipmentRentalCostLinesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a single localized equipment rental cost line..
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>EquipmentRentalCostLine</returns>
        EquipmentRentalCostLine CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGet (string catId, string id, List<string> expand = null);

        /// <summary>
        /// Gets a single localized equipment rental cost line..
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>ApiResponse of EquipmentRentalCostLine</returns>
        ApiResponse<EquipmentRentalCostLine> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGetWithHttpInfo (string catId, string id, List<string> expand = null);
        /// <summary>
        /// Gets a list of localized equipment rental cost lines.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionCode">If supplied, searches within a specified division. Accepts division codes for any level in the hierarchy (two, four, six or eight digit division codes). (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>PagedListEquipmentRentalCostLine</returns>
        PagedListEquipmentRentalCostLine CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGet (string catId, string searchTerm = null, string divisionCode = null, List<string> expand = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Gets a list of localized equipment rental cost lines.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionCode">If supplied, searches within a specified division. Accepts division codes for any level in the hierarchy (two, four, six or eight digit division codes). (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>ApiResponse of PagedListEquipmentRentalCostLine</returns>
        ApiResponse<PagedListEquipmentRentalCostLine> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGetWithHttpInfo (string catId, string searchTerm = null, string divisionCode = null, List<string> expand = null, int? offset = null, int? limit = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets a single localized equipment rental cost line..
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of EquipmentRentalCostLine</returns>
        System.Threading.Tasks.Task<EquipmentRentalCostLine> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGetAsync (string catId, string id, List<string> expand = null);

        /// <summary>
        /// Gets a single localized equipment rental cost line..
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of ApiResponse (EquipmentRentalCostLine)</returns>
        System.Threading.Tasks.Task<ApiResponse<EquipmentRentalCostLine>> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGetAsyncWithHttpInfo (string catId, string id, List<string> expand = null);
        /// <summary>
        /// Gets a list of localized equipment rental cost lines.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionCode">If supplied, searches within a specified division. Accepts division codes for any level in the hierarchy (two, four, six or eight digit division codes). (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of PagedListEquipmentRentalCostLine</returns>
        System.Threading.Tasks.Task<PagedListEquipmentRentalCostLine> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGetAsync (string catId, string searchTerm = null, string divisionCode = null, List<string> expand = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Gets a list of localized equipment rental cost lines.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionCode">If supplied, searches within a specified division. Accepts division codes for any level in the hierarchy (two, four, six or eight digit division codes). (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of ApiResponse (PagedListEquipmentRentalCostLine)</returns>
        System.Threading.Tasks.Task<ApiResponse<PagedListEquipmentRentalCostLine>> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGetAsyncWithHttpInfo (string catId, string searchTerm = null, string divisionCode = null, List<string> expand = null, int? offset = null, int? limit = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CostDataUnitEquipmentRentalCostLinesApi : ICostDataUnitEquipmentRentalCostLinesApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CostDataUnitEquipmentRentalCostLinesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CostDataUnitEquipmentRentalCostLinesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CostDataUnitEquipmentRentalCostLinesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CostDataUnitEquipmentRentalCostLinesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets a single localized equipment rental cost line.. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>EquipmentRentalCostLine</returns>
        public EquipmentRentalCostLine CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGet (string catId, string id, List<string> expand = null)
        {
             ApiResponse<EquipmentRentalCostLine> localVarResponse = CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGetWithHttpInfo(catId, id, expand);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a single localized equipment rental cost line.. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>ApiResponse of EquipmentRentalCostLine</returns>
        public ApiResponse< EquipmentRentalCostLine > CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGetWithHttpInfo (string catId, string id, List<string> expand = null)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CostDataUnitEquipmentRentalCostLinesApi->CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGet");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling CostDataUnitEquipmentRentalCostLinesApi->CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGet");

            var localVarPath = "/v1/costdata/unit/catalogs/{catId}/equipmentrentalcostlines/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (expand != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expand", expand)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EquipmentRentalCostLine>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EquipmentRentalCostLine) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EquipmentRentalCostLine)));
        }

        /// <summary>
        /// Gets a single localized equipment rental cost line.. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of EquipmentRentalCostLine</returns>
        public async System.Threading.Tasks.Task<EquipmentRentalCostLine> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGetAsync (string catId, string id, List<string> expand = null)
        {
             ApiResponse<EquipmentRentalCostLine> localVarResponse = await CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGetAsyncWithHttpInfo(catId, id, expand);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a single localized equipment rental cost line.. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of ApiResponse (EquipmentRentalCostLine)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EquipmentRentalCostLine>> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGetAsyncWithHttpInfo (string catId, string id, List<string> expand = null)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CostDataUnitEquipmentRentalCostLinesApi->CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGet");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling CostDataUnitEquipmentRentalCostLinesApi->CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGet");

            var localVarPath = "/v1/costdata/unit/catalogs/{catId}/equipmentrentalcostlines/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (expand != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expand", expand)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EquipmentRentalCostLine>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EquipmentRentalCostLine) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EquipmentRentalCostLine)));
        }

        /// <summary>
        /// Gets a list of localized equipment rental cost lines. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionCode">If supplied, searches within a specified division. Accepts division codes for any level in the hierarchy (two, four, six or eight digit division codes). (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>PagedListEquipmentRentalCostLine</returns>
        public PagedListEquipmentRentalCostLine CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGet (string catId, string searchTerm = null, string divisionCode = null, List<string> expand = null, int? offset = null, int? limit = null)
        {
             ApiResponse<PagedListEquipmentRentalCostLine> localVarResponse = CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGetWithHttpInfo(catId, searchTerm, divisionCode, expand, offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a list of localized equipment rental cost lines. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionCode">If supplied, searches within a specified division. Accepts division codes for any level in the hierarchy (two, four, six or eight digit division codes). (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>ApiResponse of PagedListEquipmentRentalCostLine</returns>
        public ApiResponse< PagedListEquipmentRentalCostLine > CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGetWithHttpInfo (string catId, string searchTerm = null, string divisionCode = null, List<string> expand = null, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CostDataUnitEquipmentRentalCostLinesApi->CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGet");

            var localVarPath = "/v1/costdata/unit/catalogs/{catId}/equipmentrentalcostlines";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (divisionCode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "divisionCode", divisionCode)); // query parameter
            if (expand != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expand", expand)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PagedListEquipmentRentalCostLine>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PagedListEquipmentRentalCostLine) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PagedListEquipmentRentalCostLine)));
        }

        /// <summary>
        /// Gets a list of localized equipment rental cost lines. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionCode">If supplied, searches within a specified division. Accepts division codes for any level in the hierarchy (two, four, six or eight digit division codes). (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of PagedListEquipmentRentalCostLine</returns>
        public async System.Threading.Tasks.Task<PagedListEquipmentRentalCostLine> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGetAsync (string catId, string searchTerm = null, string divisionCode = null, List<string> expand = null, int? offset = null, int? limit = null)
        {
             ApiResponse<PagedListEquipmentRentalCostLine> localVarResponse = await CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGetAsyncWithHttpInfo(catId, searchTerm, divisionCode, expand, offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a list of localized equipment rental cost lines. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionCode">If supplied, searches within a specified division. Accepts division codes for any level in the hierarchy (two, four, six or eight digit division codes). (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of ApiResponse (PagedListEquipmentRentalCostLine)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PagedListEquipmentRentalCostLine>> CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGetAsyncWithHttpInfo (string catId, string searchTerm = null, string divisionCode = null, List<string> expand = null, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CostDataUnitEquipmentRentalCostLinesApi->CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGet");

            var localVarPath = "/v1/costdata/unit/catalogs/{catId}/equipmentrentalcostlines";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (divisionCode != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "divisionCode", divisionCode)); // query parameter
            if (expand != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expand", expand)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CostdataUnitCatalogsByCatIdEquipmentRentalCostLinesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PagedListEquipmentRentalCostLine>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PagedListEquipmentRentalCostLine) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PagedListEquipmentRentalCostLine)));
        }

    }
}
