/* 
 * RSMeans Consumer REST API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using Gordian.DataApi.Client;
using Gordian.DataApi.Model;
using RestSharp;

namespace Gordian.DataApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICostDataAssemblyCatalogsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a single cost data catalog.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The cost data catalog identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>AssemblyCatalog</returns>
        AssemblyCatalog CostdataAssemblyCatalogsByIdGet (string id, List<string> expand = null);

        /// <summary>
        /// Gets a single cost data catalog.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The cost data catalog identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>ApiResponse of AssemblyCatalog</returns>
        ApiResponse<AssemblyCatalog> CostdataAssemblyCatalogsByIdGetWithHttpInfo (string id, List<string> expand = null);
        /// <summary>
        /// Gets a list of the available cost data catalogs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">The release identifier. Defaults to the most recent annual release. (optional)</param>
        /// <param name="locationId">The location identifier for computing localized costs. Defaults to US National Average (us-us-national). (optional)</param>
        /// <param name="laborType">Specifies standard union or open shop unit lines. Defaults to standard union (std). (optional)</param>
        /// <param name="measurementSystem">Specifies the measurement system. Defaults to Imperial units (imp). (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>NonpagedListAssemblyCatalog</returns>
        NonpagedListAssemblyCatalog CostdataAssemblyCatalogsGet (string releaseId = null, string locationId = null, string laborType = null, string measurementSystem = null, string searchTerm = null, List<string> expand = null);

        /// <summary>
        /// Gets a list of the available cost data catalogs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">The release identifier. Defaults to the most recent annual release. (optional)</param>
        /// <param name="locationId">The location identifier for computing localized costs. Defaults to US National Average (us-us-national). (optional)</param>
        /// <param name="laborType">Specifies standard union or open shop unit lines. Defaults to standard union (std). (optional)</param>
        /// <param name="measurementSystem">Specifies the measurement system. Defaults to Imperial units (imp). (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>ApiResponse of NonpagedListAssemblyCatalog</returns>
        ApiResponse<NonpagedListAssemblyCatalog> CostdataAssemblyCatalogsGetWithHttpInfo (string releaseId = null, string locationId = null, string laborType = null, string measurementSystem = null, string searchTerm = null, List<string> expand = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets a single cost data catalog.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The cost data catalog identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of AssemblyCatalog</returns>
        System.Threading.Tasks.Task<AssemblyCatalog> CostdataAssemblyCatalogsByIdGetAsync (string id, List<string> expand = null);

        /// <summary>
        /// Gets a single cost data catalog.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The cost data catalog identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of ApiResponse (AssemblyCatalog)</returns>
        System.Threading.Tasks.Task<ApiResponse<AssemblyCatalog>> CostdataAssemblyCatalogsByIdGetAsyncWithHttpInfo (string id, List<string> expand = null);
        /// <summary>
        /// Gets a list of the available cost data catalogs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">The release identifier. Defaults to the most recent annual release. (optional)</param>
        /// <param name="locationId">The location identifier for computing localized costs. Defaults to US National Average (us-us-national). (optional)</param>
        /// <param name="laborType">Specifies standard union or open shop unit lines. Defaults to standard union (std). (optional)</param>
        /// <param name="measurementSystem">Specifies the measurement system. Defaults to Imperial units (imp). (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of NonpagedListAssemblyCatalog</returns>
        System.Threading.Tasks.Task<NonpagedListAssemblyCatalog> CostdataAssemblyCatalogsGetAsync (string releaseId = null, string locationId = null, string laborType = null, string measurementSystem = null, string searchTerm = null, List<string> expand = null);

        /// <summary>
        /// Gets a list of the available cost data catalogs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">The release identifier. Defaults to the most recent annual release. (optional)</param>
        /// <param name="locationId">The location identifier for computing localized costs. Defaults to US National Average (us-us-national). (optional)</param>
        /// <param name="laborType">Specifies standard union or open shop unit lines. Defaults to standard union (std). (optional)</param>
        /// <param name="measurementSystem">Specifies the measurement system. Defaults to Imperial units (imp). (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of ApiResponse (NonpagedListAssemblyCatalog)</returns>
        System.Threading.Tasks.Task<ApiResponse<NonpagedListAssemblyCatalog>> CostdataAssemblyCatalogsGetAsyncWithHttpInfo (string releaseId = null, string locationId = null, string laborType = null, string measurementSystem = null, string searchTerm = null, List<string> expand = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CostDataAssemblyCatalogsApi : ICostDataAssemblyCatalogsApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CostDataAssemblyCatalogsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CostDataAssemblyCatalogsApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CostDataAssemblyCatalogsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CostDataAssemblyCatalogsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets a single cost data catalog. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The cost data catalog identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>AssemblyCatalog</returns>
        public AssemblyCatalog CostdataAssemblyCatalogsByIdGet (string id, List<string> expand = null)
        {
             ApiResponse<AssemblyCatalog> localVarResponse = CostdataAssemblyCatalogsByIdGetWithHttpInfo(id, expand);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a single cost data catalog. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The cost data catalog identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>ApiResponse of AssemblyCatalog</returns>
        public ApiResponse< AssemblyCatalog > CostdataAssemblyCatalogsByIdGetWithHttpInfo (string id, List<string> expand = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling CostDataAssemblyCatalogsApi->CostdataAssemblyCatalogsByIdGet");

            var localVarPath = "/v1/costdata/assembly/catalogs/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (expand != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expand", expand)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CostdataAssemblyCatalogsByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AssemblyCatalog>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AssemblyCatalog) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AssemblyCatalog)));
        }

        /// <summary>
        /// Gets a single cost data catalog. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The cost data catalog identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of AssemblyCatalog</returns>
        public async System.Threading.Tasks.Task<AssemblyCatalog> CostdataAssemblyCatalogsByIdGetAsync (string id, List<string> expand = null)
        {
             ApiResponse<AssemblyCatalog> localVarResponse = await CostdataAssemblyCatalogsByIdGetAsyncWithHttpInfo(id, expand);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a single cost data catalog. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The cost data catalog identifier.</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of ApiResponse (AssemblyCatalog)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AssemblyCatalog>> CostdataAssemblyCatalogsByIdGetAsyncWithHttpInfo (string id, List<string> expand = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling CostDataAssemblyCatalogsApi->CostdataAssemblyCatalogsByIdGet");

            var localVarPath = "/v1/costdata/assembly/catalogs/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (expand != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expand", expand)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CostdataAssemblyCatalogsByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AssemblyCatalog>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AssemblyCatalog) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AssemblyCatalog)));
        }

        /// <summary>
        /// Gets a list of the available cost data catalogs 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">The release identifier. Defaults to the most recent annual release. (optional)</param>
        /// <param name="locationId">The location identifier for computing localized costs. Defaults to US National Average (us-us-national). (optional)</param>
        /// <param name="laborType">Specifies standard union or open shop unit lines. Defaults to standard union (std). (optional)</param>
        /// <param name="measurementSystem">Specifies the measurement system. Defaults to Imperial units (imp). (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>NonpagedListAssemblyCatalog</returns>
        public NonpagedListAssemblyCatalog CostdataAssemblyCatalogsGet (string releaseId = null, string locationId = null, string laborType = null, string measurementSystem = null, string searchTerm = null, List<string> expand = null)
        {
             ApiResponse<NonpagedListAssemblyCatalog> localVarResponse = CostdataAssemblyCatalogsGetWithHttpInfo(releaseId, locationId, laborType, measurementSystem, searchTerm, expand);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a list of the available cost data catalogs 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">The release identifier. Defaults to the most recent annual release. (optional)</param>
        /// <param name="locationId">The location identifier for computing localized costs. Defaults to US National Average (us-us-national). (optional)</param>
        /// <param name="laborType">Specifies standard union or open shop unit lines. Defaults to standard union (std). (optional)</param>
        /// <param name="measurementSystem">Specifies the measurement system. Defaults to Imperial units (imp). (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>ApiResponse of NonpagedListAssemblyCatalog</returns>
        public ApiResponse< NonpagedListAssemblyCatalog > CostdataAssemblyCatalogsGetWithHttpInfo (string releaseId = null, string locationId = null, string laborType = null, string measurementSystem = null, string searchTerm = null, List<string> expand = null)
        {

            var localVarPath = "/v1/costdata/assembly/catalogs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (releaseId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "releaseId", releaseId)); // query parameter
            if (locationId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "locationId", locationId)); // query parameter
            if (laborType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "laborType", laborType)); // query parameter
            if (measurementSystem != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "measurementSystem", measurementSystem)); // query parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (expand != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expand", expand)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CostdataAssemblyCatalogsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NonpagedListAssemblyCatalog>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (NonpagedListAssemblyCatalog) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NonpagedListAssemblyCatalog)));
        }

        /// <summary>
        /// Gets a list of the available cost data catalogs 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">The release identifier. Defaults to the most recent annual release. (optional)</param>
        /// <param name="locationId">The location identifier for computing localized costs. Defaults to US National Average (us-us-national). (optional)</param>
        /// <param name="laborType">Specifies standard union or open shop unit lines. Defaults to standard union (std). (optional)</param>
        /// <param name="measurementSystem">Specifies the measurement system. Defaults to Imperial units (imp). (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of NonpagedListAssemblyCatalog</returns>
        public async System.Threading.Tasks.Task<NonpagedListAssemblyCatalog> CostdataAssemblyCatalogsGetAsync (string releaseId = null, string locationId = null, string laborType = null, string measurementSystem = null, string searchTerm = null, List<string> expand = null)
        {
             ApiResponse<NonpagedListAssemblyCatalog> localVarResponse = await CostdataAssemblyCatalogsGetAsyncWithHttpInfo(releaseId, locationId, laborType, measurementSystem, searchTerm, expand);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a list of the available cost data catalogs 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseId">The release identifier. Defaults to the most recent annual release. (optional)</param>
        /// <param name="locationId">The location identifier for computing localized costs. Defaults to US National Average (us-us-national). (optional)</param>
        /// <param name="laborType">Specifies standard union or open shop unit lines. Defaults to standard union (std). (optional)</param>
        /// <param name="measurementSystem">Specifies the measurement system. Defaults to Imperial units (imp). (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="expand">A list of properties to expand. Applies only to expandable properties. (optional)</param>
        /// <returns>Task of ApiResponse (NonpagedListAssemblyCatalog)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<NonpagedListAssemblyCatalog>> CostdataAssemblyCatalogsGetAsyncWithHttpInfo (string releaseId = null, string locationId = null, string laborType = null, string measurementSystem = null, string searchTerm = null, List<string> expand = null)
        {

            var localVarPath = "/v1/costdata/assembly/catalogs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (releaseId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "releaseId", releaseId)); // query parameter
            if (locationId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "locationId", locationId)); // query parameter
            if (laborType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "laborType", laborType)); // query parameter
            if (measurementSystem != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "measurementSystem", measurementSystem)); // query parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (expand != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "expand", expand)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CostdataAssemblyCatalogsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NonpagedListAssemblyCatalog>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (NonpagedListAssemblyCatalog) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NonpagedListAssemblyCatalog)));
        }

    }
}
