/* 
 * RSMeans Consumer REST API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using Gordian.DataApi.Client;
using Gordian.DataApi.Model;
using RestSharp;

namespace Gordian.DataApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICTCCostLinesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a single CTC cost line.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <returns>CostLineDto</returns>
        CostLineDto CtcCatalogsByCatIdCostLinesByIdGet (string catId, string id);

        /// <summary>
        /// Gets a single CTC cost line.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <returns>ApiResponse of CostLineDto</returns>
        ApiResponse<CostLineDto> CtcCatalogsByCatIdCostLinesByIdGetWithHttpInfo (string catId, string id);
        /// <summary>
        /// Gets a list of CTC cost lines.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>PagedListCostLineDto</returns>
        PagedListCostLineDto CtcCatalogsByCatIdCostLinesGet (string catId, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Gets a list of CTC cost lines.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>ApiResponse of PagedListCostLineDto</returns>
        ApiResponse<PagedListCostLineDto> CtcCatalogsByCatIdCostLinesGetWithHttpInfo (string catId, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null);
        /// <summary>
        /// Gets a list of CTC cost lines with aggregations at the top division level.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="includeDivisionCount">If true, the search result will include the number of unit lines that match the key word search for each division. Defaults to true. (optional)</param>
        /// <param name="includeCostLines">If true, the search result will include unit lines that match the key word search. Defaults to true. (optional)</param>
        /// <param name="sortByLineNumber">If true, the search result will sorted by CSI numbers. Defaults to true. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>CostLineSearchResultDto</returns>
        CostLineSearchResultDto CtcCatalogsByCatIdCostLinesSearchGet (string catId, bool? includeDivisionCount = null, bool? includeCostLines = null, bool? sortByLineNumber = null, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Gets a list of CTC cost lines with aggregations at the top division level.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="includeDivisionCount">If true, the search result will include the number of unit lines that match the key word search for each division. Defaults to true. (optional)</param>
        /// <param name="includeCostLines">If true, the search result will include unit lines that match the key word search. Defaults to true. (optional)</param>
        /// <param name="sortByLineNumber">If true, the search result will sorted by CSI numbers. Defaults to true. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>ApiResponse of CostLineSearchResultDto</returns>
        ApiResponse<CostLineSearchResultDto> CtcCatalogsByCatIdCostLinesSearchGetWithHttpInfo (string catId, bool? includeDivisionCount = null, bool? includeCostLines = null, bool? sortByLineNumber = null, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets a single CTC cost line.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <returns>Task of CostLineDto</returns>
        System.Threading.Tasks.Task<CostLineDto> CtcCatalogsByCatIdCostLinesByIdGetAsync (string catId, string id);

        /// <summary>
        /// Gets a single CTC cost line.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <returns>Task of ApiResponse (CostLineDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<CostLineDto>> CtcCatalogsByCatIdCostLinesByIdGetAsyncWithHttpInfo (string catId, string id);
        /// <summary>
        /// Gets a list of CTC cost lines.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of PagedListCostLineDto</returns>
        System.Threading.Tasks.Task<PagedListCostLineDto> CtcCatalogsByCatIdCostLinesGetAsync (string catId, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Gets a list of CTC cost lines.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of ApiResponse (PagedListCostLineDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<PagedListCostLineDto>> CtcCatalogsByCatIdCostLinesGetAsyncWithHttpInfo (string catId, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null);
        /// <summary>
        /// Gets a list of CTC cost lines with aggregations at the top division level.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="includeDivisionCount">If true, the search result will include the number of unit lines that match the key word search for each division. Defaults to true. (optional)</param>
        /// <param name="includeCostLines">If true, the search result will include unit lines that match the key word search. Defaults to true. (optional)</param>
        /// <param name="sortByLineNumber">If true, the search result will sorted by CSI numbers. Defaults to true. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of CostLineSearchResultDto</returns>
        System.Threading.Tasks.Task<CostLineSearchResultDto> CtcCatalogsByCatIdCostLinesSearchGetAsync (string catId, bool? includeDivisionCount = null, bool? includeCostLines = null, bool? sortByLineNumber = null, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null);

        /// <summary>
        /// Gets a list of CTC cost lines with aggregations at the top division level.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="includeDivisionCount">If true, the search result will include the number of unit lines that match the key word search for each division. Defaults to true. (optional)</param>
        /// <param name="includeCostLines">If true, the search result will include unit lines that match the key word search. Defaults to true. (optional)</param>
        /// <param name="sortByLineNumber">If true, the search result will sorted by CSI numbers. Defaults to true. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of ApiResponse (CostLineSearchResultDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<CostLineSearchResultDto>> CtcCatalogsByCatIdCostLinesSearchGetAsyncWithHttpInfo (string catId, bool? includeDivisionCount = null, bool? includeCostLines = null, bool? sortByLineNumber = null, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CTCCostLinesApi : ICTCCostLinesApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CTCCostLinesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CTCCostLinesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CTCCostLinesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CTCCostLinesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets a single CTC cost line. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <returns>CostLineDto</returns>
        public CostLineDto CtcCatalogsByCatIdCostLinesByIdGet (string catId, string id)
        {
             ApiResponse<CostLineDto> localVarResponse = CtcCatalogsByCatIdCostLinesByIdGetWithHttpInfo(catId, id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a single CTC cost line. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <returns>ApiResponse of CostLineDto</returns>
        public ApiResponse< CostLineDto > CtcCatalogsByCatIdCostLinesByIdGetWithHttpInfo (string catId, string id)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CTCCostLinesApi->CtcCatalogsByCatIdCostLinesByIdGet");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling CTCCostLinesApi->CtcCatalogsByCatIdCostLinesByIdGet");

            var localVarPath = "/v1/ctc/catalogs/{catId}/costlines/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CtcCatalogsByCatIdCostLinesByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CostLineDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CostLineDto) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CostLineDto)));
        }

        /// <summary>
        /// Gets a single CTC cost line. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <returns>Task of CostLineDto</returns>
        public async System.Threading.Tasks.Task<CostLineDto> CtcCatalogsByCatIdCostLinesByIdGetAsync (string catId, string id)
        {
             ApiResponse<CostLineDto> localVarResponse = await CtcCatalogsByCatIdCostLinesByIdGetAsyncWithHttpInfo(catId, id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a single CTC cost line. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="id">The unit line identifier.</param>
        /// <returns>Task of ApiResponse (CostLineDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CostLineDto>> CtcCatalogsByCatIdCostLinesByIdGetAsyncWithHttpInfo (string catId, string id)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CTCCostLinesApi->CtcCatalogsByCatIdCostLinesByIdGet");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling CTCCostLinesApi->CtcCatalogsByCatIdCostLinesByIdGet");

            var localVarPath = "/v1/ctc/catalogs/{catId}/costlines/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CtcCatalogsByCatIdCostLinesByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CostLineDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CostLineDto) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CostLineDto)));
        }

        /// <summary>
        /// Gets a list of CTC cost lines. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>PagedListCostLineDto</returns>
        public PagedListCostLineDto CtcCatalogsByCatIdCostLinesGet (string catId, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null)
        {
             ApiResponse<PagedListCostLineDto> localVarResponse = CtcCatalogsByCatIdCostLinesGetWithHttpInfo(catId, searchTerm, divisionId, offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a list of CTC cost lines. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>ApiResponse of PagedListCostLineDto</returns>
        public ApiResponse< PagedListCostLineDto > CtcCatalogsByCatIdCostLinesGetWithHttpInfo (string catId, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CTCCostLinesApi->CtcCatalogsByCatIdCostLinesGet");

            var localVarPath = "/v1/ctc/catalogs/{catId}/costlines";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (divisionId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "divisionId", divisionId)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CtcCatalogsByCatIdCostLinesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PagedListCostLineDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PagedListCostLineDto) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PagedListCostLineDto)));
        }

        /// <summary>
        /// Gets a list of CTC cost lines. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of PagedListCostLineDto</returns>
        public async System.Threading.Tasks.Task<PagedListCostLineDto> CtcCatalogsByCatIdCostLinesGetAsync (string catId, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null)
        {
             ApiResponse<PagedListCostLineDto> localVarResponse = await CtcCatalogsByCatIdCostLinesGetAsyncWithHttpInfo(catId, searchTerm, divisionId, offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a list of CTC cost lines. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of ApiResponse (PagedListCostLineDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PagedListCostLineDto>> CtcCatalogsByCatIdCostLinesGetAsyncWithHttpInfo (string catId, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CTCCostLinesApi->CtcCatalogsByCatIdCostLinesGet");

            var localVarPath = "/v1/ctc/catalogs/{catId}/costlines";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (divisionId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "divisionId", divisionId)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CtcCatalogsByCatIdCostLinesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PagedListCostLineDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PagedListCostLineDto) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PagedListCostLineDto)));
        }

        /// <summary>
        /// Gets a list of CTC cost lines with aggregations at the top division level. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="includeDivisionCount">If true, the search result will include the number of unit lines that match the key word search for each division. Defaults to true. (optional)</param>
        /// <param name="includeCostLines">If true, the search result will include unit lines that match the key word search. Defaults to true. (optional)</param>
        /// <param name="sortByLineNumber">If true, the search result will sorted by CSI numbers. Defaults to true. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>CostLineSearchResultDto</returns>
        public CostLineSearchResultDto CtcCatalogsByCatIdCostLinesSearchGet (string catId, bool? includeDivisionCount = null, bool? includeCostLines = null, bool? sortByLineNumber = null, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null)
        {
             ApiResponse<CostLineSearchResultDto> localVarResponse = CtcCatalogsByCatIdCostLinesSearchGetWithHttpInfo(catId, includeDivisionCount, includeCostLines, sortByLineNumber, searchTerm, divisionId, offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a list of CTC cost lines with aggregations at the top division level. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="includeDivisionCount">If true, the search result will include the number of unit lines that match the key word search for each division. Defaults to true. (optional)</param>
        /// <param name="includeCostLines">If true, the search result will include unit lines that match the key word search. Defaults to true. (optional)</param>
        /// <param name="sortByLineNumber">If true, the search result will sorted by CSI numbers. Defaults to true. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>ApiResponse of CostLineSearchResultDto</returns>
        public ApiResponse< CostLineSearchResultDto > CtcCatalogsByCatIdCostLinesSearchGetWithHttpInfo (string catId, bool? includeDivisionCount = null, bool? includeCostLines = null, bool? sortByLineNumber = null, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CTCCostLinesApi->CtcCatalogsByCatIdCostLinesSearchGet");

            var localVarPath = "/v1/ctc/catalogs/{catId}/costlines/_search";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (includeDivisionCount != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeDivisionCount", includeDivisionCount)); // query parameter
            if (includeCostLines != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeCostLines", includeCostLines)); // query parameter
            if (sortByLineNumber != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "sortByLineNumber", sortByLineNumber)); // query parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (divisionId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "divisionId", divisionId)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CtcCatalogsByCatIdCostLinesSearchGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CostLineSearchResultDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CostLineSearchResultDto) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CostLineSearchResultDto)));
        }

        /// <summary>
        /// Gets a list of CTC cost lines with aggregations at the top division level. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="includeDivisionCount">If true, the search result will include the number of unit lines that match the key word search for each division. Defaults to true. (optional)</param>
        /// <param name="includeCostLines">If true, the search result will include unit lines that match the key word search. Defaults to true. (optional)</param>
        /// <param name="sortByLineNumber">If true, the search result will sorted by CSI numbers. Defaults to true. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of CostLineSearchResultDto</returns>
        public async System.Threading.Tasks.Task<CostLineSearchResultDto> CtcCatalogsByCatIdCostLinesSearchGetAsync (string catId, bool? includeDivisionCount = null, bool? includeCostLines = null, bool? sortByLineNumber = null, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null)
        {
             ApiResponse<CostLineSearchResultDto> localVarResponse = await CtcCatalogsByCatIdCostLinesSearchGetAsyncWithHttpInfo(catId, includeDivisionCount, includeCostLines, sortByLineNumber, searchTerm, divisionId, offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a list of CTC cost lines with aggregations at the top division level. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="catId">The catalog identifier.</param>
        /// <param name="includeDivisionCount">If true, the search result will include the number of unit lines that match the key word search for each division. Defaults to true. (optional)</param>
        /// <param name="includeCostLines">If true, the search result will include unit lines that match the key word search. Defaults to true. (optional)</param>
        /// <param name="sortByLineNumber">If true, the search result will sorted by CSI numbers. Defaults to true. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only unit lines containing the specified search terms. (optional)</param>
        /// <param name="divisionId">If supplied, searches within a specified division. (optional)</param>
        /// <param name="offset">For paging, specify the offset from which to start returning results. Defaults to zero. (optional)</param>
        /// <param name="limit">For paging, specify the maximum number of unit lines to return in a single request. Defaults to 25 and Max value is 100. (optional)</param>
        /// <returns>Task of ApiResponse (CostLineSearchResultDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CostLineSearchResultDto>> CtcCatalogsByCatIdCostLinesSearchGetAsyncWithHttpInfo (string catId, bool? includeDivisionCount = null, bool? includeCostLines = null, bool? sortByLineNumber = null, string searchTerm = null, string divisionId = null, int? offset = null, int? limit = null)
        {
            // verify the required parameter 'catId' is set
            if (catId == null)
                throw new ApiException(400, "Missing required parameter 'catId' when calling CTCCostLinesApi->CtcCatalogsByCatIdCostLinesSearchGet");

            var localVarPath = "/v1/ctc/catalogs/{catId}/costlines/_search";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (catId != null) localVarPathParams.Add("catId", this.Configuration.ApiClient.ParameterToString(catId)); // path parameter
            if (includeDivisionCount != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeDivisionCount", includeDivisionCount)); // query parameter
            if (includeCostLines != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeCostLines", includeCostLines)); // query parameter
            if (sortByLineNumber != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "sortByLineNumber", sortByLineNumber)); // query parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (divisionId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "divisionId", divisionId)); // query parameter
            if (offset != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "offset", offset)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("CtcCatalogsByCatIdCostLinesSearchGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CostLineSearchResultDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CostLineSearchResultDto) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CostLineSearchResultDto)));
        }

    }
}
