/* 
 * RSMeans Consumer REST API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using Gordian.DataApi.Client;
using Gordian.DataApi.Model;
using RestSharp;

namespace Gordian.DataApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISquareFootModelCommercialModelsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a commercial model by Id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The model Id, for example 2017-001.</param>
        /// <returns>CommercialBuildingType</returns>
        CommercialBuildingType SquarefootmodelCommercialModelsByIdGet (string id);

        /// <summary>
        /// Gets a commercial model by Id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The model Id, for example 2017-001.</param>
        /// <returns>ApiResponse of CommercialBuildingType</returns>
        ApiResponse<CommercialBuildingType> SquarefootmodelCommercialModelsByIdGetWithHttpInfo (string id);
        /// <summary>
        /// Gets a list of commercial models.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseYear">The release year. Defaults to the most recent anual release. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only models containing the specified search terms in descriptions. (optional)</param>
        /// <returns>NonpagedListCommercialBuildingType</returns>
        NonpagedListCommercialBuildingType SquarefootmodelCommercialModelsGet (string releaseYear = null, string searchTerm = null);

        /// <summary>
        /// Gets a list of commercial models.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseYear">The release year. Defaults to the most recent anual release. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only models containing the specified search terms in descriptions. (optional)</param>
        /// <returns>ApiResponse of NonpagedListCommercialBuildingType</returns>
        ApiResponse<NonpagedListCommercialBuildingType> SquarefootmodelCommercialModelsGetWithHttpInfo (string releaseYear = null, string searchTerm = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets a commercial model by Id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The model Id, for example 2017-001.</param>
        /// <returns>Task of CommercialBuildingType</returns>
        System.Threading.Tasks.Task<CommercialBuildingType> SquarefootmodelCommercialModelsByIdGetAsync (string id);

        /// <summary>
        /// Gets a commercial model by Id.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The model Id, for example 2017-001.</param>
        /// <returns>Task of ApiResponse (CommercialBuildingType)</returns>
        System.Threading.Tasks.Task<ApiResponse<CommercialBuildingType>> SquarefootmodelCommercialModelsByIdGetAsyncWithHttpInfo (string id);
        /// <summary>
        /// Gets a list of commercial models.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseYear">The release year. Defaults to the most recent anual release. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only models containing the specified search terms in descriptions. (optional)</param>
        /// <returns>Task of NonpagedListCommercialBuildingType</returns>
        System.Threading.Tasks.Task<NonpagedListCommercialBuildingType> SquarefootmodelCommercialModelsGetAsync (string releaseYear = null, string searchTerm = null);

        /// <summary>
        /// Gets a list of commercial models.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseYear">The release year. Defaults to the most recent anual release. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only models containing the specified search terms in descriptions. (optional)</param>
        /// <returns>Task of ApiResponse (NonpagedListCommercialBuildingType)</returns>
        System.Threading.Tasks.Task<ApiResponse<NonpagedListCommercialBuildingType>> SquarefootmodelCommercialModelsGetAsyncWithHttpInfo (string releaseYear = null, string searchTerm = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SquareFootModelCommercialModelsApi : ISquareFootModelCommercialModelsApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SquareFootModelCommercialModelsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SquareFootModelCommercialModelsApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SquareFootModelCommercialModelsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SquareFootModelCommercialModelsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets a commercial model by Id. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The model Id, for example 2017-001.</param>
        /// <returns>CommercialBuildingType</returns>
        public CommercialBuildingType SquarefootmodelCommercialModelsByIdGet (string id)
        {
             ApiResponse<CommercialBuildingType> localVarResponse = SquarefootmodelCommercialModelsByIdGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a commercial model by Id. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The model Id, for example 2017-001.</param>
        /// <returns>ApiResponse of CommercialBuildingType</returns>
        public ApiResponse< CommercialBuildingType > SquarefootmodelCommercialModelsByIdGetWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling SquareFootModelCommercialModelsApi->SquarefootmodelCommercialModelsByIdGet");

            var localVarPath = "/v1/squarefootmodel/commercial/models/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("SquarefootmodelCommercialModelsByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CommercialBuildingType>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CommercialBuildingType) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CommercialBuildingType)));
        }

        /// <summary>
        /// Gets a commercial model by Id. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The model Id, for example 2017-001.</param>
        /// <returns>Task of CommercialBuildingType</returns>
        public async System.Threading.Tasks.Task<CommercialBuildingType> SquarefootmodelCommercialModelsByIdGetAsync (string id)
        {
             ApiResponse<CommercialBuildingType> localVarResponse = await SquarefootmodelCommercialModelsByIdGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a commercial model by Id. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The model Id, for example 2017-001.</param>
        /// <returns>Task of ApiResponse (CommercialBuildingType)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CommercialBuildingType>> SquarefootmodelCommercialModelsByIdGetAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling SquareFootModelCommercialModelsApi->SquarefootmodelCommercialModelsByIdGet");

            var localVarPath = "/v1/squarefootmodel/commercial/models/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("SquarefootmodelCommercialModelsByIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CommercialBuildingType>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CommercialBuildingType) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CommercialBuildingType)));
        }

        /// <summary>
        /// Gets a list of commercial models. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseYear">The release year. Defaults to the most recent anual release. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only models containing the specified search terms in descriptions. (optional)</param>
        /// <returns>NonpagedListCommercialBuildingType</returns>
        public NonpagedListCommercialBuildingType SquarefootmodelCommercialModelsGet (string releaseYear = null, string searchTerm = null)
        {
             ApiResponse<NonpagedListCommercialBuildingType> localVarResponse = SquarefootmodelCommercialModelsGetWithHttpInfo(releaseYear, searchTerm);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a list of commercial models. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseYear">The release year. Defaults to the most recent anual release. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only models containing the specified search terms in descriptions. (optional)</param>
        /// <returns>ApiResponse of NonpagedListCommercialBuildingType</returns>
        public ApiResponse< NonpagedListCommercialBuildingType > SquarefootmodelCommercialModelsGetWithHttpInfo (string releaseYear = null, string searchTerm = null)
        {

            var localVarPath = "/v1/squarefootmodel/commercial/models";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (releaseYear != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "releaseYear", releaseYear)); // query parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("SquarefootmodelCommercialModelsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NonpagedListCommercialBuildingType>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (NonpagedListCommercialBuildingType) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NonpagedListCommercialBuildingType)));
        }

        /// <summary>
        /// Gets a list of commercial models. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseYear">The release year. Defaults to the most recent anual release. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only models containing the specified search terms in descriptions. (optional)</param>
        /// <returns>Task of NonpagedListCommercialBuildingType</returns>
        public async System.Threading.Tasks.Task<NonpagedListCommercialBuildingType> SquarefootmodelCommercialModelsGetAsync (string releaseYear = null, string searchTerm = null)
        {
             ApiResponse<NonpagedListCommercialBuildingType> localVarResponse = await SquarefootmodelCommercialModelsGetAsyncWithHttpInfo(releaseYear, searchTerm);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a list of commercial models. 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="releaseYear">The release year. Defaults to the most recent anual release. (optional)</param>
        /// <param name="searchTerm">If supplied, returns only models containing the specified search terms in descriptions. (optional)</param>
        /// <returns>Task of ApiResponse (NonpagedListCommercialBuildingType)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<NonpagedListCommercialBuildingType>> SquarefootmodelCommercialModelsGetAsyncWithHttpInfo (string releaseYear = null, string searchTerm = null)
        {

            var localVarPath = "/v1/squarefootmodel/commercial/models";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (releaseYear != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "releaseYear", releaseYear)); // query parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter

            // authentication (rsmids_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = this.ExceptionFactory("SquarefootmodelCommercialModelsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NonpagedListCommercialBuildingType>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (NonpagedListCommercialBuildingType) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NonpagedListCommercialBuildingType)));
        }

    }
}
