/* 
 * RSMeans Consumer REST API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Gordian.DataApi.Model
{
    /// <summary>
    /// AssemblyCostLine
    /// </summary>
    [DataContract]
    public partial class AssemblyCostLine : IEquatable<AssemblyCostLine>, IValidatableObject
    {
        /// <summary>
        /// Defines CostDataFormat
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CostDataFormatEnum
        {

            /// <summary>
            /// Enum Uni for value: uni
            /// </summary>
            [EnumMember(Value = "uni")]
            Uni = 1,

            /// <summary>
            /// Enum Resi for value: resi
            /// </summary>
            [EnumMember(Value = "resi")]
            Resi = 2
        }

        /// <summary>
        /// Gets or Sets CostDataFormat
        /// </summary>
        [DataMember(Name = "costDataFormat", EmitDefaultValue = false)]
        public CostDataFormatEnum? CostDataFormat { get; set; }
        /// <summary>
        /// Defines MeasurementSystem
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MeasurementSystemEnum
        {

            /// <summary>
            /// Enum Imp for value: imp
            /// </summary>
            [EnumMember(Value = "imp")]
            Imp = 1,

            /// <summary>
            /// Enum Met for value: met
            /// </summary>
            [EnumMember(Value = "met")]
            Met = 2
        }

        /// <summary>
        /// Gets or Sets MeasurementSystem
        /// </summary>
        [DataMember(Name = "measurementSystem", EmitDefaultValue = false)]
        public MeasurementSystemEnum? MeasurementSystem { get; set; }
        /// <summary>
        /// Defines LaborType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LaborTypeEnum
        {

            /// <summary>
            /// Enum Std for value: std
            /// </summary>
            [EnumMember(Value = "std")]
            Std = 1,

            /// <summary>
            /// Enum Opn for value: opn
            /// </summary>
            [EnumMember(Value = "opn")]
            Opn = 2,

            /// <summary>
            /// Enum Fmr for value: fmr
            /// </summary>
            [EnumMember(Value = "fmr")]
            Fmr = 3,

            /// <summary>
            /// Enum Res for value: res
            /// </summary>
            [EnumMember(Value = "res")]
            Res = 4,

            /// <summary>
            /// Enum Rr for value: rr
            /// </summary>
            [EnumMember(Value = "rr")]
            Rr = 5,

            /// <summary>
            /// Enum Fed for value: fed
            /// </summary>
            [EnumMember(Value = "fed")]
            Fed = 6
        }

        /// <summary>
        /// Gets or Sets LaborType
        /// </summary>
        [DataMember(Name = "laborType", EmitDefaultValue = false)]
        public LaborTypeEnum? LaborType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AssemblyCostLine" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="lineNumber">lineNumber.</param>
        /// <param name="release">release.</param>
        /// <param name="catalog">catalog.</param>
        /// <param name="costDataFormat">costDataFormat.</param>
        /// <param name="measurementSystem">measurementSystem.</param>
        /// <param name="laborType">laborType.</param>
        /// <param name="frequency">frequency.</param>
        /// <param name="division">division.</param>
        /// <param name="shortDescription">shortDescription.</param>
        /// <param name="description">description.</param>
        /// <param name="unitOfMeasure">unitOfMeasure.</param>
        /// <param name="crew">crew.</param>
        /// <param name="baseCosts">baseCosts.</param>
        /// <param name="location">location.</param>
        /// <param name="costFactors">costFactors.</param>
        /// <param name="localizedCosts">localizedCosts.</param>
        /// <param name="assemblyUnitCostLines">assemblyUnitCostLines.</param>
        public AssemblyCostLine(string id = default(string), string lineNumber = default(string), ReferenceRelease release = default(ReferenceRelease), ReferenceAssemblyCatalog catalog = default(ReferenceAssemblyCatalog), CostDataFormatEnum? costDataFormat = default(CostDataFormatEnum?), MeasurementSystemEnum? measurementSystem = default(MeasurementSystemEnum?), LaborTypeEnum? laborType = default(LaborTypeEnum?), double? frequency = default(double?), ReferenceAssemblyDivision division = default(ReferenceAssemblyDivision), string shortDescription = default(string), string description = default(string), string unitOfMeasure = default(string), LineCrew crew = default(LineCrew), AssemblyLineCostData baseCosts = default(AssemblyLineCostData), ReferenceLocation location = default(ReferenceLocation), CostFactorData costFactors = default(CostFactorData), LocalAssemblyLineCostData localizedCosts = default(LocalAssemblyLineCostData), ReferenceListAssemblyUnitLineComponent assemblyUnitCostLines = default(ReferenceListAssemblyUnitLineComponent))
        {
            this.Id = id;
            this.LineNumber = lineNumber;
            this.Release = release;
            this.Catalog = catalog;
            this.CostDataFormat = costDataFormat;
            this.MeasurementSystem = measurementSystem;
            this.LaborType = laborType;
            this.Frequency = frequency;
            this.Division = division;
            this.ShortDescription = shortDescription;
            this.Description = description;
            this.UnitOfMeasure = unitOfMeasure;
            this.Crew = crew;
            this.BaseCosts = baseCosts;
            this.Location = location;
            this.CostFactors = costFactors;
            this.LocalizedCosts = localizedCosts;
            this.AssemblyUnitCostLines = assemblyUnitCostLines;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        [BsonId]
        public string MongoId { get; set; }

        /// <summary>
        /// Gets or Sets LineNumber
        /// </summary>
        [DataMember(Name = "lineNumber", EmitDefaultValue = false)]
        public string LineNumber { get; set; }

        /// <summary>
        /// Gets or Sets Release
        /// </summary>
        [DataMember(Name = "release", EmitDefaultValue = false)]
        public ReferenceRelease Release { get; set; }

        /// <summary>
        /// Gets or Sets Catalog
        /// </summary>
        [DataMember(Name = "catalog", EmitDefaultValue = false)]
        public ReferenceAssemblyCatalog Catalog { get; set; }




        /// <summary>
        /// Gets or Sets Frequency
        /// </summary>
        [DataMember(Name = "frequency", EmitDefaultValue = false)]
        public double? Frequency { get; set; }

        /// <summary>
        /// Gets or Sets Division
        /// </summary>
        [DataMember(Name = "division", EmitDefaultValue = false)]
        public ReferenceAssemblyDivision Division { get; set; }

        /// <summary>
        /// Gets or Sets ShortDescription
        /// </summary>
        [DataMember(Name = "shortDescription", EmitDefaultValue = false)]
        public string ShortDescription { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets UnitOfMeasure
        /// </summary>
        [DataMember(Name = "unitOfMeasure", EmitDefaultValue = false)]
        public string UnitOfMeasure { get; set; }

        /// <summary>
        /// Gets or Sets Crew
        /// </summary>
        [DataMember(Name = "crew", EmitDefaultValue = false)]
        public LineCrew Crew { get; set; }

        /// <summary>
        /// Gets or Sets BaseCosts
        /// </summary>
        [DataMember(Name = "baseCosts", EmitDefaultValue = false)]
        public AssemblyLineCostData BaseCosts { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", EmitDefaultValue = false)]
        public ReferenceLocation Location { get; set; }

        /// <summary>
        /// Gets or Sets CostFactors
        /// </summary>
        [DataMember(Name = "costFactors", EmitDefaultValue = false)]
        public CostFactorData CostFactors { get; set; }

        /// <summary>
        /// Gets or Sets LocalizedCosts
        /// </summary>
        [DataMember(Name = "localizedCosts", EmitDefaultValue = false)]
        public LocalAssemblyLineCostData LocalizedCosts { get; set; }

        /// <summary>
        /// Gets or Sets AssemblyUnitCostLines
        /// </summary>
        [DataMember(Name = "assemblyUnitCostLines", EmitDefaultValue = false)]
        public ReferenceListAssemblyUnitLineComponent AssemblyUnitCostLines { get; set; }

        /// <summary>
        /// Gets or Sets Href
        /// </summary>
        [DataMember(Name = "href", EmitDefaultValue = false)]
        public string Href { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssemblyCostLine {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LineNumber: ").Append(LineNumber).Append("\n");
            sb.Append("  Release: ").Append(Release).Append("\n");
            sb.Append("  Catalog: ").Append(Catalog).Append("\n");
            sb.Append("  CostDataFormat: ").Append(CostDataFormat).Append("\n");
            sb.Append("  MeasurementSystem: ").Append(MeasurementSystem).Append("\n");
            sb.Append("  LaborType: ").Append(LaborType).Append("\n");
            sb.Append("  Frequency: ").Append(Frequency).Append("\n");
            sb.Append("  Division: ").Append(Division).Append("\n");
            sb.Append("  ShortDescription: ").Append(ShortDescription).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  UnitOfMeasure: ").Append(UnitOfMeasure).Append("\n");
            sb.Append("  Crew: ").Append(Crew).Append("\n");
            sb.Append("  BaseCosts: ").Append(BaseCosts).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  CostFactors: ").Append(CostFactors).Append("\n");
            sb.Append("  LocalizedCosts: ").Append(LocalizedCosts).Append("\n");
            sb.Append("  AssemblyUnitCostLines: ").Append(AssemblyUnitCostLines).Append("\n");
            sb.Append("  Href: ").Append(Href).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssemblyCostLine);
        }

        /// <summary>
        /// Returns true if AssemblyCostLine instances are equal
        /// </summary>
        /// <param name="input">Instance of AssemblyCostLine to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssemblyCostLine input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) &&
                (
                    this.LineNumber == input.LineNumber ||
                    (this.LineNumber != null &&
                    this.LineNumber.Equals(input.LineNumber))
                ) &&
                (
                    this.Release == input.Release ||
                    (this.Release != null &&
                    this.Release.Equals(input.Release))
                ) &&
                (
                    this.Catalog == input.Catalog ||
                    (this.Catalog != null &&
                    this.Catalog.Equals(input.Catalog))
                ) &&
                (
                    this.CostDataFormat == input.CostDataFormat ||
                    (this.CostDataFormat != null &&
                    this.CostDataFormat.Equals(input.CostDataFormat))
                ) &&
                (
                    this.MeasurementSystem == input.MeasurementSystem ||
                    (this.MeasurementSystem != null &&
                    this.MeasurementSystem.Equals(input.MeasurementSystem))
                ) &&
                (
                    this.LaborType == input.LaborType ||
                    (this.LaborType != null &&
                    this.LaborType.Equals(input.LaborType))
                ) &&
                (
                    this.Frequency == input.Frequency ||
                    (this.Frequency != null &&
                    this.Frequency.Equals(input.Frequency))
                ) &&
                (
                    this.Division == input.Division ||
                    (this.Division != null &&
                    this.Division.Equals(input.Division))
                ) &&
                (
                    this.ShortDescription == input.ShortDescription ||
                    (this.ShortDescription != null &&
                    this.ShortDescription.Equals(input.ShortDescription))
                ) &&
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) &&
                (
                    this.UnitOfMeasure == input.UnitOfMeasure ||
                    (this.UnitOfMeasure != null &&
                    this.UnitOfMeasure.Equals(input.UnitOfMeasure))
                ) &&
                (
                    this.Crew == input.Crew ||
                    (this.Crew != null &&
                    this.Crew.Equals(input.Crew))
                ) &&
                (
                    this.BaseCosts == input.BaseCosts ||
                    (this.BaseCosts != null &&
                    this.BaseCosts.Equals(input.BaseCosts))
                ) &&
                (
                    this.Location == input.Location ||
                    (this.Location != null &&
                    this.Location.Equals(input.Location))
                ) &&
                (
                    this.CostFactors == input.CostFactors ||
                    (this.CostFactors != null &&
                    this.CostFactors.Equals(input.CostFactors))
                ) &&
                (
                    this.LocalizedCosts == input.LocalizedCosts ||
                    (this.LocalizedCosts != null &&
                    this.LocalizedCosts.Equals(input.LocalizedCosts))
                ) &&
                (
                    this.AssemblyUnitCostLines == input.AssemblyUnitCostLines ||
                    (this.AssemblyUnitCostLines != null &&
                    this.AssemblyUnitCostLines.Equals(input.AssemblyUnitCostLines))
                ) &&
                (
                    this.Href == input.Href ||
                    (this.Href != null &&
                    this.Href.Equals(input.Href))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.LineNumber != null)
                    hashCode = hashCode * 59 + this.LineNumber.GetHashCode();
                if (this.Release != null)
                    hashCode = hashCode * 59 + this.Release.GetHashCode();
                if (this.Catalog != null)
                    hashCode = hashCode * 59 + this.Catalog.GetHashCode();
                if (this.CostDataFormat != null)
                    hashCode = hashCode * 59 + this.CostDataFormat.GetHashCode();
                if (this.MeasurementSystem != null)
                    hashCode = hashCode * 59 + this.MeasurementSystem.GetHashCode();
                if (this.LaborType != null)
                    hashCode = hashCode * 59 + this.LaborType.GetHashCode();
                if (this.Frequency != null)
                    hashCode = hashCode * 59 + this.Frequency.GetHashCode();
                if (this.Division != null)
                    hashCode = hashCode * 59 + this.Division.GetHashCode();
                if (this.ShortDescription != null)
                    hashCode = hashCode * 59 + this.ShortDescription.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.UnitOfMeasure != null)
                    hashCode = hashCode * 59 + this.UnitOfMeasure.GetHashCode();
                if (this.Crew != null)
                    hashCode = hashCode * 59 + this.Crew.GetHashCode();
                if (this.BaseCosts != null)
                    hashCode = hashCode * 59 + this.BaseCosts.GetHashCode();
                if (this.Location != null)
                    hashCode = hashCode * 59 + this.Location.GetHashCode();
                if (this.CostFactors != null)
                    hashCode = hashCode * 59 + this.CostFactors.GetHashCode();
                if (this.LocalizedCosts != null)
                    hashCode = hashCode * 59 + this.LocalizedCosts.GetHashCode();
                if (this.AssemblyUnitCostLines != null)
                    hashCode = hashCode * 59 + this.AssemblyUnitCostLines.GetHashCode();
                if (this.Href != null)
                    hashCode = hashCode * 59 + this.Href.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
