/* 
 * RSMeans Consumer REST API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Gordian.DataApi.Model
{
    /// <summary>
    /// ExtendedCostViewModel
    /// </summary>
    [DataContract]
    public partial class ExtendedCostViewModel :  IEquatable<ExtendedCostViewModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtendedCostViewModel" /> class.
        /// </summary>
        /// <param name="totalCost">totalCost.</param>
        /// <param name="materialCost">materialCost.</param>
        /// <param name="laborCost">laborCost.</param>
        /// <param name="equipmentCost">equipmentCost.</param>
        public ExtendedCostViewModel(ExtendedDetailedCost totalCost = default(ExtendedDetailedCost), ExtendedDetailedCost materialCost = default(ExtendedDetailedCost), ExtendedDetailedCost laborCost = default(ExtendedDetailedCost), ExtendedDetailedCost equipmentCost = default(ExtendedDetailedCost))
        {
            this.TotalCost = totalCost;
            this.MaterialCost = materialCost;
            this.LaborCost = laborCost;
            this.EquipmentCost = equipmentCost;
        }
        
        /// <summary>
        /// Gets or Sets TotalCost
        /// </summary>
        [DataMember(Name="totalCost", EmitDefaultValue=false)]
        public ExtendedDetailedCost TotalCost { get; set; }

        /// <summary>
        /// Gets or Sets MaterialCost
        /// </summary>
        [DataMember(Name="materialCost", EmitDefaultValue=false)]
        public ExtendedDetailedCost MaterialCost { get; set; }

        /// <summary>
        /// Gets or Sets LaborCost
        /// </summary>
        [DataMember(Name="laborCost", EmitDefaultValue=false)]
        public ExtendedDetailedCost LaborCost { get; set; }

        /// <summary>
        /// Gets or Sets EquipmentCost
        /// </summary>
        [DataMember(Name="equipmentCost", EmitDefaultValue=false)]
        public ExtendedDetailedCost EquipmentCost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExtendedCostViewModel {\n");
            sb.Append("  TotalCost: ").Append(TotalCost).Append("\n");
            sb.Append("  MaterialCost: ").Append(MaterialCost).Append("\n");
            sb.Append("  LaborCost: ").Append(LaborCost).Append("\n");
            sb.Append("  EquipmentCost: ").Append(EquipmentCost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExtendedCostViewModel);
        }

        /// <summary>
        /// Returns true if ExtendedCostViewModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ExtendedCostViewModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExtendedCostViewModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TotalCost == input.TotalCost ||
                    (this.TotalCost != null &&
                    this.TotalCost.Equals(input.TotalCost))
                ) && 
                (
                    this.MaterialCost == input.MaterialCost ||
                    (this.MaterialCost != null &&
                    this.MaterialCost.Equals(input.MaterialCost))
                ) && 
                (
                    this.LaborCost == input.LaborCost ||
                    (this.LaborCost != null &&
                    this.LaborCost.Equals(input.LaborCost))
                ) && 
                (
                    this.EquipmentCost == input.EquipmentCost ||
                    (this.EquipmentCost != null &&
                    this.EquipmentCost.Equals(input.EquipmentCost))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TotalCost != null)
                    hashCode = hashCode * 59 + this.TotalCost.GetHashCode();
                if (this.MaterialCost != null)
                    hashCode = hashCode * 59 + this.MaterialCost.GetHashCode();
                if (this.LaborCost != null)
                    hashCode = hashCode * 59 + this.LaborCost.GetHashCode();
                if (this.EquipmentCost != null)
                    hashCode = hashCode * 59 + this.EquipmentCost.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
