/* 
 * RSMeans Consumer REST API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Gordian.DataApi.Model
{
    /// <summary>
    /// RangedParameterDecimal
    /// </summary>
    [DataContract]
    public partial class RangedParameterDecimal :  IEquatable<RangedParameterDecimal>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RangedParameterDecimal" /> class.
        /// </summary>
        /// <param name="minValue">The min value.</param>
        /// <param name="maxValue">The max value..</param>
        /// <param name="defaultValue">The default value..</param>
        /// <param name="currentValue">The current value..</param>
        public RangedParameterDecimal(double? minValue = default(double?), double? maxValue = default(double?), double? defaultValue = default(double?), double? currentValue = default(double?))
        {
            this.MinValue = minValue;
            this.MaxValue = maxValue;
            this.DefaultValue = defaultValue;
            this.CurrentValue = currentValue;
        }
        
        /// <summary>
        /// The min value
        /// </summary>
        /// <value>The min value</value>
        [DataMember(Name="minValue", EmitDefaultValue=false)]
        public double? MinValue { get; set; }

        /// <summary>
        /// The max value.
        /// </summary>
        /// <value>The max value.</value>
        [DataMember(Name="maxValue", EmitDefaultValue=false)]
        public double? MaxValue { get; set; }

        /// <summary>
        /// The default value.
        /// </summary>
        /// <value>The default value.</value>
        [DataMember(Name="defaultValue", EmitDefaultValue=false)]
        public double? DefaultValue { get; set; }

        /// <summary>
        /// The current value.
        /// </summary>
        /// <value>The current value.</value>
        [DataMember(Name="currentValue", EmitDefaultValue=false)]
        public double? CurrentValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RangedParameterDecimal {\n");
            sb.Append("  MinValue: ").Append(MinValue).Append("\n");
            sb.Append("  MaxValue: ").Append(MaxValue).Append("\n");
            sb.Append("  DefaultValue: ").Append(DefaultValue).Append("\n");
            sb.Append("  CurrentValue: ").Append(CurrentValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RangedParameterDecimal);
        }

        /// <summary>
        /// Returns true if RangedParameterDecimal instances are equal
        /// </summary>
        /// <param name="input">Instance of RangedParameterDecimal to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RangedParameterDecimal input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MinValue == input.MinValue ||
                    (this.MinValue != null &&
                    this.MinValue.Equals(input.MinValue))
                ) && 
                (
                    this.MaxValue == input.MaxValue ||
                    (this.MaxValue != null &&
                    this.MaxValue.Equals(input.MaxValue))
                ) && 
                (
                    this.DefaultValue == input.DefaultValue ||
                    (this.DefaultValue != null &&
                    this.DefaultValue.Equals(input.DefaultValue))
                ) && 
                (
                    this.CurrentValue == input.CurrentValue ||
                    (this.CurrentValue != null &&
                    this.CurrentValue.Equals(input.CurrentValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MinValue != null)
                    hashCode = hashCode * 59 + this.MinValue.GetHashCode();
                if (this.MaxValue != null)
                    hashCode = hashCode * 59 + this.MaxValue.GetHashCode();
                if (this.DefaultValue != null)
                    hashCode = hashCode * 59 + this.DefaultValue.GetHashCode();
                if (this.CurrentValue != null)
                    hashCode = hashCode * 59 + this.CurrentValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
